spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/order

order:
  queue: OrderQueue
  exchange: OrderExchange
  routingkey: OrderKey

server:
  error:
    include-message: always